sonar.projectKey=myapp
sonar.projectName=MyApp
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
# sonar.login=<TOKEN>    ← Jenkins se run kar rahe ho to is line ko skip karo
