# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkar-war-deploy
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: jenkar-war
#   template:
#     metadata:
#       labels:
#         app: jenkar-war
#     spec:
#       containers:
#       - name: jenkar-war-container
#         image: anantlaghane/jenkar-war-deploy:latest
#         ports:
#         - containerPort: 8085


apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkar-war-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkar-war
  template:
    metadata:
      labels:
        app: jenkar-war
    spec:
      containers:
      - name: jenkar-war-container
        image: anantlaghane/jenkar-war-deploy:latest
        ports:
        - containerPort: 8085
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 20
