apiVersion: v1
kind: Service
metadata:
  name: jenkar-war-service
spec:
  type: NodePort
  selector:
    app: jenkar-war-deploy  
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
