apiVersion: v1
kind: Service
metadata:
  name: jenkar-war-service
spec:
  type: NodePort
  selector:
    app: jenkar-war 
  ports:
    - port: 80
      targetPort: 8085
      nodePort: 31000
      protocol: TCP
